const DEPARTMENTS: Department[] = [
    {
        id: 8,
        name: 'Ardennes',
        nameSlug: 'ardennes',
        hometown: 'Charleville-Mézières',
        hometownSlug: 'charlevillemezieres',
        region: 0,
    },
    {
        id: 10,
        name: 'Aube',
        nameSlug: 'aube',
        hometown: 'Troyes',
        hometownSlug: 'troyes',
        region: 0,
    },
    {
        id: 51,
        name: 'Marne',
        nameSlug: 'marne',
        hometown: 'Châlons-en-Champagne',
        hometownSlug: 'chalonsenchampagne',
        region: 0,
    },
    {
        id: 52,
        name: 'Haute-Marne',
        nameSlug: 'hautemarne',
        hometown: 'Chaumont',
        hometownSlug: 'chaumont',
        region: 0,
    },
    {
        id: 54,
        name: 'Meurthe-et-Moselle',
        nameSlug: 'meurtheetmoselle',
        hometown: 'Nancy',
        hometownSlug: 'nancy',
        region: 0,
    },
    {
        id: 55,
        name: 'Meuse',
        nameSlug: 'meuse',
        hometown: 'Bar-le-Duc',
        hometownSlug: 'barleduc',
        region: 0,
    },
    {
        id: 57,
        name: 'Moselle',
        nameSlug: 'moselle',
        hometown: 'Metz',
        hometownSlug: 'metz',
        region: 0,
    },
    {
        id: 67,
        name: 'Bas-Rhin',
        nameSlug: 'basrhin',
        hometown: 'strasbourg',
        hometownSlug: 'strasbourg',
        region: 0,
    },
    {
        id: 68,
        name: 'Haut-Rhin',
        nameSlug: 'hautrhin',
        hometown: 'colmar',
        hometownSlug: 'colmar',
        region: 0,
    },
    {
        id: 88,
        name: 'Vosges',
        nameSlug: 'vosges',
        hometown: 'Épinal',
        hometownSlug: 'epinal',
        region: 0,
    },
    {
        id: 2,
        name: 'Aisne',
        nameSlug: 'aisne',
        hometown: 'Laon',
        hometownSlug: 'laon',
        region: 1,
    },
    {
        id: 59,
        name: 'Nord',
        nameSlug: 'nord',
        hometown: 'Lille',
        hometownSlug: 'lille',
        region: 1,
    },
    {
        id: 60,
        name: 'Oise',
        nameSlug: 'oise',
        hometown: 'Beauvais',
        hometownSlug: 'beauvais',
        region: 1,
    },
    {
        id: 62,
        name: 'Pas-de-Calais',
        nameSlug: 'pasdecalais',
        hometown: 'Arras',
        hometownSlug: 'arras',
        region: 1,
    },
    {
        id: 80,
        name: 'Somme',
        nameSlug: 'somme',
        hometown: 'Amiens',
        hometownSlug: 'amiens',
        region: 1,
    },
    {
        id: 75,
        name: 'Paris',
        nameSlug: 'paris',
        hometown: 'Paris',
        hometownSlug: 'paris',
        region: 2,
    },
    {
        id: 77,
        name: 'Seine-et-Marne',
        nameSlug: 'seineetmarne',
        hometown: 'Melun',
        hometownSlug: 'melun',
        region: 2,
    },
    {
        id: 78,
        name: 'Yvelines',
        nameSlug: 'yvelines',
        hometown: 'Versailles',
        hometownSlug: 'versailles',
        region: 2,
    },
    {
        id: 91,
        name: 'Essonne',
        nameSlug: 'essonne',
        hometown: 'Évry-Courcouronnes',
        hometownSlug: 'evrycourcouronnes',
        region: 2,
    },
    {
        id: 92,
        name: 'Hauts-de-Seine',
        nameSlug: 'hautsdeseine',
        hometown: 'Nanterre',
        hometownSlug: 'nanterre',
        region: 2,
    },
    {
        id: 93,
        name: 'Seine-Saint-Denis',
        nameSlug: 'seinesaintdenis',
        hometown: 'Bobigny',
        hometownSlug: 'bobigny',
        region: 2,
    },
    {
        id: 94,
        name: 'Val-de-Marne',
        nameSlug: 'valdemarne',
        hometown: 'Créteil',
        hometownSlug: 'creteil',
        region: 2,
    },
    {
        id: 95,
        name: 'Val-d’Oise',
        nameSlug: 'valdoise',
        hometown: 'Pontoise',
        hometownSlug: 'pontoise',
        region: 2,
    },
    {
        id: 21,
        name: 'Côte-d’Or',
        nameSlug: 'cotedor',
        hometown: 'Dijon',
        hometownSlug: 'dijon',
        region: 3,
    },
    {
        id: 25,
        name: 'Doubs',
        nameSlug: 'doubs',
        hometown: 'Besançon',
        hometownSlug: 'besancon',
        region: 3,
    },
    {
        id: 39,
        name: 'Jura',
        nameSlug: 'jura',
        hometown: 'Lons-le-Saunier',
        hometownSlug: 'lonslesaunier',
        region: 3,
    },
    {
        id: 58,
        name: 'Nièvre',
        nameSlug: 'nievre',
        hometown: 'Nevers',
        hometownSlug: 'nevers',
        region: 3,
    },
    {
        id: 70,
        name: 'Haute-Saône',
        nameSlug: 'hautesaone',
        hometown: 'Vesoul',
        hometownSlug: 'vesoul',
        region: 3,
    },
    {
        id: 71,
        name: 'Saône-et-Loire',
        nameSlug: 'saoneetloire',
        hometown: 'Mâcon',
        hometownSlug: 'macon',
        region: 3,
    },
    {
        id: 89,
        name: 'Yonne',
        nameSlug: 'yonne',
        hometown: 'Auxerre',
        hometownSlug: 'auxerre',
        region: 3,
    },
    {
        id: 90,
        name: 'Territoire de Belfort',
        nameSlug: 'territoiredebelfort',
        hometown: 'Belfort',
        hometownSlug: 'belfort',
        region: 3,
    },
    {
        id: 18,
        name: 'Cher',
        nameSlug: 'cher',
        hometown: 'Bourges',
        hometownSlug: 'bourges',
        region: 4,
    },
    {
        id: 28,
        name: 'Eure-et-Loir',
        nameSlug: 'eureetloir',
        hometown: 'Chartres',
        hometownSlug: 'chartres',
        region: 4,
    },
    {
        id: 36,
        name: 'Indre',
        nameSlug: 'indre',
        hometown: 'Châteauroux',
        hometownSlug: 'chateauroux',
        region: 4,
    },
    {
        id: 37,
        name: 'Indre-et-Loire',
        nameSlug: 'indreetloire',
        hometown: 'Tours',
        hometownSlug: 'tours',
        region: 4,
    },
    {
        id: 41,
        name: 'Loir-et-Cher',
        nameSlug: 'loiretcher',
        hometown: 'Blois',
        hometownSlug: 'blois',
        region: 4,
    },
    {
        id: 45,
        name: 'Loiret',
        nameSlug: 'loiret',
        hometown: 'Orléans',
        hometownSlug: 'orleans',
        region: 4,
    },
    {
        id: 1,
        name: 'Ain',
        nameSlug: 'ain',
        hometown: 'Bourg-en-Bresse',
        hometownSlug: 'bourgenbresse',
        region: 5,
    },
    {
        id: 3,
        name: 'Allier',
        nameSlug: 'allier',
        hometown: 'Moulins',
        hometownSlug: 'moulins',
        region: 5,
    },
    {
        id: 7,
        name: 'Ardèche',
        nameSlug: 'ardeche',
        hometown: 'Privas',
        hometownSlug: 'privas',
        region: 5,
    },
    {
        id: 15,
        name: 'Cantal',
        nameSlug: 'cantal',
        hometown: 'Aurillac',
        hometownSlug: 'aurillac',
        region: 5,
    },
    {
        id: 26,
        name: 'Drôme',
        nameSlug: 'drome',
        hometown: 'Valence',
        hometownSlug: 'valence',
        region: 5,
    },
    {
        id: 38,
        name: 'Isère',
        nameSlug: 'isere',
        hometown: 'Grenoble',
        hometownSlug: 'grenoble',
        region: 5,
    },
    {
        id: 42,
        name: 'Loire',
        nameSlug: 'loire',
        hometown: 'Saint-Étienne',
        hometownSlug: 'saintetienne',
        region: 5,
    },
    {
        id: 43,
        name: 'Haute-Loire',
        nameSlug: 'hauteloire',
        hometown: 'Le Puy-en-Velay',
        hometownSlug: 'lepuyenvelay',
        region: 5,
    },
    {
        id: 63,
        name: 'Puy-de-Dôme',
        nameSlug: 'puydedome',
        hometown: 'Clermont-Ferrand',
        hometownSlug: 'clermontferrand',
        region: 5,
    },
    {
        id: 69,
        name: 'Rhône',
        nameSlug: 'rhone',
        hometown: 'Lyon',
        hometownSlug: 'lyon',
        region: 5,
    },
    {
        id: 73,
        name: 'Savoie',
        nameSlug: 'savoie',
        hometown: 'Chambéry',
        hometownSlug: 'chambery',
        region: 5,
    },
    {
        id: 74,
        name: 'Haute-Savoie',
        nameSlug: 'hautesavoie',
        hometown: 'Annecy',
        hometownSlug: 'annecy',
        region: 5,
    },
    {
        id: 16,
        name: 'Charente',
        nameSlug: 'charente',
        hometown: 'Angoulême',
        hometownSlug: 'angouleme',
        region: 6,
    },
    {
        id: 17,
        name: 'Charente-Maritime',
        nameSlug: 'charentemaritime',
        hometown: 'La Rochelle',
        hometownSlug: 'larochelle',
        region: 6,
    },
    {
        id: 19,
        name: 'Corrèze',
        nameSlug: 'correze',
        hometown: 'Tulle',
        hometownSlug: 'tulle',
        region: 6,
    },
    {
        id: 23,
        name: 'Creuse',
        nameSlug: 'creuse',
        hometown: 'Guéret',
        hometownSlug: 'gueret',
        region: 6,
    },
    {
        id: 24,
        name: 'Dordogne',
        nameSlug: 'dordogne',
        hometown: 'Périgueux',
        hometownSlug: 'perigueux',
        region: 6,
    },
    {
        id: 33,
        name: 'Gironde',
        nameSlug: 'gironde',
        hometown: 'Bordeaux',
        hometownSlug: 'bordeaux',
        region: 6,
    },
    {
        id: 40,
        name: 'Landes',
        nameSlug: 'landes',
        hometown: 'Mont-de-Marsan',
        hometownSlug: 'montdemarsan',
        region: 6,
    },
    {
        id: 47,
        name: 'Lot-et-Garonne',
        nameSlug: 'lotetgaronne',
        hometown: 'Agen',
        hometownSlug: 'agen',
        region: 6,
    },
    {
        id: 64,
        name: 'Pyrénées-Atlantiques',
        nameSlug: 'pyreneesatlantiques',
        hometown: 'Pau',
        hometownSlug: 'pau',
        region: 6,
    },
    {
        id: 79,
        name: 'Deux-Sèvres',
        nameSlug: 'deuxsevres',
        hometown: 'Niort',
        hometownSlug: 'niort',
        region: 6,
    },
    {
        id: 86,
        name: 'Vienne',
        nameSlug: 'vienne',
        hometown: 'Poitiers',
        hometownSlug: 'poitiers',
        region: 6,
    },
    {
        id: 87,
        name: 'Haute-Vienne',
        nameSlug: 'hautevienne',
        hometown: 'limoges',
        hometownSlug: 'limoges',
        region: 6,
    },
    {
        id: 14,
        name: 'Calvados',
        nameSlug: 'calvados',
        hometown: 'Caen',
        hometownSlug: 'caen',
        region: 7,
    },
    {
        id: 27,
        name: 'Eure',
        nameSlug: 'eure',
        hometown: 'Évreux',
        hometownSlug: 'evreux',
        region: 7,
    },
    {
        id: 50,
        name: 'Manche',
        nameSlug: 'manche',
        hometown: 'Saint-Lô',
        hometownSlug: 'saintlo',
        region: 7,
    },
    {
        id: 61,
        name: 'Orne',
        nameSlug: 'orne',
        hometown: 'Alençon',
        hometownSlug: 'alencon',
        region: 7,
    },
    {
        id: 76,
        name: 'Seine-Maritime',
        nameSlug: 'seinemaritime',
        hometown: 'Rouen',
        hometownSlug: 'rouen',
        region: 7,
    },
    {
        id: 22,
        name: 'Côtes-d’Armor',
        nameSlug: 'cotesdarmor',
        hometown: 'Saint-Brieuc',
        hometownSlug: 'saintbrieuc',
        region: 8,
    },
    {
        id: 29,
        name: 'Finistère',
        nameSlug: 'finistere',
        hometown: 'Quimper',
        hometownSlug: 'quimper',
        region: 8,
    },
    {
        id: 35,
        name: 'Ille-et-Vilaine',
        nameSlug: 'illeetvilaine',
        hometown: 'Rennes',
        hometownSlug: 'rennes',
        region: 8,
    },
    {
        id: 56,
        name: 'Morbihan',
        nameSlug: 'morbihan',
        hometown: 'Vannes',
        hometownSlug: 'vannes',
        region: 8,
    },
    {
        id: 44,
        name: 'Loire-Atlantique',
        nameSlug: 'loireatlantique',
        hometown: 'Nantes',
        hometownSlug: 'nantes',
        region: 9,
    },
    {
        id: 49,
        name: 'Maine-et-Loire',
        nameSlug: 'maineetloire',
        hometown: 'Angers',
        hometownSlug: 'angers',
        region: 9,
    },
    {
        id: 53,
        name: 'Mayenne',
        nameSlug: 'mayenne',
        hometown: 'Laval',
        hometownSlug: 'laval',
        region: 9,
    },
    {
        id: 72,
        name: 'Sarthe',
        nameSlug: 'sarthe',
        hometown: 'Le Mans',
        hometownSlug: 'lemans',
        region: 9,
    },
    {
        id: 85,
        name: 'Vendée',
        nameSlug: 'vendee',
        hometown: 'La Roche-sur-Yon',
        hometownSlug: 'larochesuryon',
        region: 9,
    },
    {
        id: 9,
        name: 'Ariège',
        nameSlug: 'ariege',
        hometown: 'Foix',
        hometownSlug: 'foix',
        region: 10,
    },
    {
        id: 11,
        name: 'Aude',
        nameSlug: 'aude',
        hometown: 'Carcassonne',
        hometownSlug: 'carcassonne',
        region: 10,
    },
    {
        id: 12,
        name: 'Aveyron',
        nameSlug: 'aveyron',
        hometown: 'Rodez',
        hometownSlug: 'rodez',
        region: 10,
    },
    {
        id: 30,
        name: 'Gard',
        nameSlug: 'gard',
        hometown: 'Nîmes',
        hometownSlug: 'nimes',
        region: 10,
    },
    {
        id: 31,
        name: 'Haute-Garonne',
        nameSlug: 'hautegaronne',
        hometown: 'Toulouse',
        hometownSlug: 'toulouse',
        region: 10,
    },
    {
        id: 32,
        name: 'Gers',
        nameSlug: 'gers',
        hometown: 'Auch',
        hometownSlug: 'auch',
        region: 10,
    },
    {
        id: 34,
        name: 'Hérault',
        nameSlug: 'herault',
        hometown: 'Montpellier',
        hometownSlug: 'montpellier',
        region: 10,
    },
    {
        id: 46,
        name: 'Lot',
        nameSlug: 'lot',
        hometown: 'Cahors',
        hometownSlug: 'cahors',
        region: 10,
    },
    {
        id: 48,
        name: 'Lozère',
        nameSlug: 'lozere',
        hometown: 'Mende',
        hometownSlug: 'mende',
        region: 10,
    },
    {
        id: 65,
        name: 'Hautes-Pyrénées',
        nameSlug: 'hautespyrenees',
        hometown: 'Tarbes',
        hometownSlug: 'tarbes',
        region: 10,
    },
    {
        id: 66,
        name: 'Pyrénées-Orientales',
        nameSlug: 'pyreneesorientales',
        hometown: 'Perpignan',
        hometownSlug: 'perpignan',
        region: 10,
    },
    {
        id: 81,
        name: 'Tarn',
        nameSlug: 'tarn',
        hometown: 'Albi',
        hometownSlug: 'albi',
        region: 10,
    },
    {
        id: 82,
        name: 'Tarn-et-Garonne',
        nameSlug: 'tarnetgaronne',
        hometown: 'Montauban',
        hometownSlug: 'montauban',
        region: 10,
    },
    {
        id: 4,
        name: 'Alpes-de-Haute-Provence',
        nameSlug: 'alpesdehauteprovence',
        hometown: 'Digne-les-Bains',
        hometownSlug: 'dignelesbains',
        region: 11,
    },
    {
        id: 5,
        name: 'Hautes-Alpes',
        nameSlug: 'hautesalpes',
        hometown: 'Gap',
        hometownSlug: 'gap',
        region: 11,
    },
    {
        id: 6,
        name: 'Alpes-Maritimes',
        nameSlug: 'alpesmaritimes',
        hometown: 'Nice',
        hometownSlug: 'nice',
        region: 11,
    },
    {
        id: 13,
        name: 'Bouches-du-Rhône',
        nameSlug: 'bouchesdurhone',
        hometown: 'Marseille',
        hometownSlug: 'marseille',
        region: 11,
    },
    {
        id: 83,
        name: 'Var',
        nameSlug: 'var',
        hometown: 'Toulon',
        hometownSlug: 'toulon',
        region: 11,
    },
    {
        id: 84,
        name: 'Vaucluse',
        nameSlug: 'vaucluse',
        hometown: 'Avignon',
        hometownSlug: 'avignon',
        region: 11,
    },
    {
        id: '2A',
        name: 'Corse-du-Sud',
        nameSlug: 'corsedusud',
        hometown: 'Ajaccio',
        hometownSlug: 'ajaccio',
        region: 12,
    },
    {
        id: '2B',
        name: 'Haute-Corse',
        nameSlug: 'hautecorse',
        hometown: 'Bastia',
        hometownSlug: 'bastia',
        region: 12,
    },
];

export default DEPARTMENTS;
